#!/bin/bash
# ============================================================================
# Optima EC2 Bootstrap Script
# Run this ONCE on a fresh Ubuntu 22.04 EC2 instance.
#
# Usage (as root or via user-data):
#   curl -fsSL https://your-s3-bucket/ec2-setup.sh | sudo bash
#
# Or via SSH after launch:
#   scp deploy/ec2-setup.sh ubuntu@EC2_IP:/tmp/
#   ssh ubuntu@EC2_IP "sudo bash /tmp/ec2-setup.sh"
#
# Required env vars (or edit defaults below):
#   PROPERTY_ID    - integer (e.g. 2)
#   PROPERTY_SLUG  - slug (e.g. acme-corp)
#   PROPERTY_DOMAIN - domain (e.g. acme.optima.sclera.com)
#   GIT_REPO       - your git repo URL
#   JWT_SECRET     - 64-char random string
# ============================================================================

set -euo pipefail

# ── Configurable defaults ─────────────────────────────────────────────────────
PROPERTY_ID="${PROPERTY_ID:-1}"
PROPERTY_SLUG="${PROPERTY_SLUG:-headquarters}"
PROPERTY_DOMAIN="${PROPERTY_DOMAIN:-app.optima.sclera.com}"
GIT_REPO="${GIT_REPO:-https://github.com/YOUR_ORG/optima.git}"
GIT_BRANCH="${GIT_BRANCH:-main}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
APP_DIR="/opt/optima"
DATA_DIR="${APP_DIR}/data"
LOG_DIR="${APP_DIR}/logs"
NODE_VERSION="20"

echo "============================================="
echo "  Optima EC2 Setup"
echo "  Property  : ${PROPERTY_SLUG} (id=${PROPERTY_ID})"
echo "  Domain    : ${PROPERTY_DOMAIN}"
echo "  App dir   : ${APP_DIR}"
echo "============================================="

# ── 1. System update ─────────────────────────────────────────────────────────
echo "[1/10] Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq git curl wget unzip nginx certbot python3-certbot-nginx \
    build-essential python3 htop ufw fail2ban

# ── 2. Node.js 20 via NodeSource ─────────────────────────────────────────────
echo "[2/10] Installing Node.js ${NODE_VERSION}..."
if ! command -v node &>/dev/null || [[ "$(node -v)" != v${NODE_VERSION}* ]]; then
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
    apt-get install -y nodejs
fi
echo "  Node: $(node -v)  npm: $(npm -v)"

# ── 3. PM2 (process manager) ─────────────────────────────────────────────────
echo "[3/10] Installing PM2..."
npm install -g pm2 --silent

# ── 4. Directory structure ────────────────────────────────────────────────────
echo "[4/10] Creating directory structure..."
mkdir -p "${APP_DIR}" "${DATA_DIR}" "${LOG_DIR}"

# ── 5. EBS data volume (mount /dev/xvdb → /opt/optima/data) ──────────────────
echo "[5/10] Configuring EBS data volume..."
EBS_DEVICE="/dev/xvdb"
if [ -b "${EBS_DEVICE}" ]; then
    # Format only if not already formatted
    if ! blkid "${EBS_DEVICE}" &>/dev/null; then
        echo "  Formatting ${EBS_DEVICE}..."
        mkfs -t ext4 "${EBS_DEVICE}"
    fi
    # Add to fstab for auto-mount on reboot
    if ! grep -q "${EBS_DEVICE}" /etc/fstab; then
        echo "${EBS_DEVICE}  ${DATA_DIR}  ext4  defaults,nofail  0  2" >> /etc/fstab
    fi
    mount -a
    echo "  EBS volume mounted at ${DATA_DIR}"
else
    echo "  No EBS at ${EBS_DEVICE} — using root volume (OK for dev/test)"
fi
chown -R ubuntu:ubuntu "${DATA_DIR}"

# ── 6. Clone / pull application code ─────────────────────────────────────────
echo "[6/10] Deploying application code..."
if [ -d "${APP_DIR}/.git" ]; then
    echo "  Pulling latest from ${GIT_BRANCH}..."
    cd "${APP_DIR}" && sudo -u ubuntu git pull origin "${GIT_BRANCH}"
else
    echo "  Cloning ${GIT_REPO}..."
    sudo -u ubuntu git clone --branch "${GIT_BRANCH}" "${GIT_REPO}" "${APP_DIR}"
fi

# ── 7. Install dependencies & build ──────────────────────────────────────────
echo "[7/10] Installing dependencies..."
cd "${APP_DIR}/optima/backend"
sudo -u ubuntu npm ci --omit=dev

echo "  Building frontend..."
cd "${APP_DIR}/optima/frontend"
sudo -u ubuntu npm ci
sudo -u ubuntu npm run build
chown -R ubuntu:ubuntu "${APP_DIR}/optima/frontend/dist"

# ── 8. Write .env ─────────────────────────────────────────────────────────────
echo "[8/10] Writing environment config..."
cat > "${APP_DIR}/.env" <<EOF
# Auto-generated by ec2-setup.sh — edit as needed
PROPERTY_ID=${PROPERTY_ID}
PROPERTY_SLUG=${PROPERTY_SLUG}
PORT=5000
NODE_ENV=production
DB_PATH=${DATA_DIR}/optima.db
JWT_SECRET=${JWT_SECRET}
ALLOWED_ORIGIN=https://${PROPERTY_DOMAIN}
EOF
chown ubuntu:ubuntu "${APP_DIR}/.env"
chmod 600 "${APP_DIR}/.env"

# ── 9. Copy PM2 + Nginx configs ───────────────────────────────────────────────
echo "[9/10] Configuring PM2 and Nginx..."

# PM2 ecosystem
cp "${APP_DIR}/optima/deploy/pm2.ecosystem.config.js" "${APP_DIR}/ecosystem.config.js"
sed -i "s|/opt/optima/.env|${APP_DIR}/.env|g" "${APP_DIR}/ecosystem.config.js"
sed -i "s|/opt/optima/backend|${APP_DIR}/optima/backend|g" "${APP_DIR}/ecosystem.config.js"
sed -i "s|/opt/optima/logs|${LOG_DIR}|g" "${APP_DIR}/ecosystem.config.js"
chown ubuntu:ubuntu "${APP_DIR}/ecosystem.config.js"

# Nginx vhost
cp "${APP_DIR}/optima/deploy/nginx.conf" /etc/nginx/sites-available/optima
sed -i "s/PROPERTY_DOMAIN/${PROPERTY_DOMAIN}/g" /etc/nginx/sites-available/optima
# Update frontend path
sed -i "s|/opt/optima/frontend/dist|${APP_DIR}/optima/frontend/dist|g" /etc/nginx/sites-available/optima

# Enable site, disable default
ln -sf /etc/nginx/sites-available/optima /etc/nginx/sites-enabled/optima
rm -f /etc/nginx/sites-enabled/default

# Temporarily serve HTTP only (Certbot will handle SSL in next step)
# Strip SSL block so nginx starts without certs
sed -i '/listen 443/,/^}/d' /etc/nginx/sites-available/optima
sed -i 's/return 301.*//' /etc/nginx/sites-available/optima
sed -i 's|listen 80.*|listen 80;|' /etc/nginx/sites-available/optima

nginx -t && systemctl reload nginx

# ── 10. Start PM2 + SSL ───────────────────────────────────────────────────────
echo "[10/10] Starting application with PM2..."
cd "${APP_DIR}"
sudo -u ubuntu pm2 start ecosystem.config.js
sudo -u ubuntu pm2 save
pm2 startup systemd -u ubuntu --hp /home/ubuntu | tail -1 | bash

echo ""
echo "  Getting SSL certificate for ${PROPERTY_DOMAIN}..."
certbot --nginx -d "${PROPERTY_DOMAIN}" \
    --non-interactive --agree-tos --email "admin@${PROPERTY_DOMAIN}" \
    --redirect

# Restore SSL config now that certs exist
cp "${APP_DIR}/optima/deploy/nginx.conf" /etc/nginx/sites-available/optima
sed -i "s/PROPERTY_DOMAIN/${PROPERTY_DOMAIN}/g" /etc/nginx/sites-available/optima
sed -i "s|/opt/optima/frontend/dist|${APP_DIR}/optima/frontend/dist|g" /etc/nginx/sites-available/optima
nginx -t && systemctl reload nginx

# ── Firewall ──────────────────────────────────────────────────────────────────
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 'Nginx Full'
ufw --force enable

echo ""
echo "============================================="
echo "  ✅  Setup complete!"
echo "  App  : https://${PROPERTY_DOMAIN}"
echo "  Health: https://${PROPERTY_DOMAIN}/health"
echo "  PM2  : pm2 status"
echo "  Logs : pm2 logs optima-${PROPERTY_SLUG}"
echo "============================================="
