#!/bin/bash
# =============================================================================
# Optima Property Client — Interactive Installer
# Supports Ubuntu 22.04/24.04 and Amazon Linux 2023
#
# This script prompts for the PROPERTY KEY generated by the central portal,
# validates it against the central server, then configures and starts the
# property backend automatically.
#
# Usage:
#   curl -fsSL https://optima.sclera.com/install/property | sudo bash
#   # or:
#   sudo bash install.sh
# =============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Defaults ──────────────────────────────────────────────────────────────────
PORTAL_URL="${PORTAL_URL:-https://optima.sclera.com}"
GIT_REPO="${GIT_REPO:-https://github.com/YOUR_ORG/optima.git}"
GIT_BRANCH="${GIT_BRANCH:-main}"
APP_DIR="/opt/optima-property"
DATA_DIR="${APP_DIR}/data"
LOG_DIR="${APP_DIR}/logs"
APP_PORT="5000"
APP_USER="optima"
NODE_VERSION="20"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           Optima Property Client Installer v7.1.2           ║"
echo "║                    optima.sclera.com                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── 1. Prompt for property key ────────────────────────────────────────────────
echo "To register this server as an Optima property instance, you need"
echo "a PROPERTY KEY generated from the central portal."
echo ""
echo "  How to get your key:"
echo "  1. Log in to https://optima.sclera.com"
echo "  2. Go to Property List → Add Property (or click a property card)"
echo "  3. Copy the Property Key shown"
echo ""

while true; do
    read -rp "$(echo -e "${BLUE}Enter Property Key${NC}: ")" PROPERTY_KEY
    PROPERTY_KEY="${PROPERTY_KEY// /}"  # strip spaces

    if [ -z "$PROPERTY_KEY" ]; then
        error "Property key cannot be empty. Please try again."
        continue
    fi

    # Validate key against central server
    info "Validating key against ${PORTAL_URL}..."
    RESPONSE=$(curl -sf -X POST "${PORTAL_URL}/api/portal/verify-key" \
        -H "Content-Type: application/json" \
        -d "{\"property_key\":\"${PROPERTY_KEY}\"}" 2>/dev/null || echo "CONNECTION_FAILED")

    if [ "$RESPONSE" = "CONNECTION_FAILED" ]; then
        error "Could not reach ${PORTAL_URL}. Check that the portal is running and the URL is correct."
        read -rp "Retry with different portal URL? [y/N]: " retry
        [[ "$retry" =~ ^[Yy]$ ]] && read -rp "Portal URL: " PORTAL_URL || exit 1
        continue
    fi

    VALID=$(echo "$RESPONSE" | grep -o '"valid":true' || true)
    if [ -z "$VALID" ]; then
        ERROR_MSG=$(echo "$RESPONSE" | grep -o '"error":"[^"]*"' | cut -d'"' -f4 || echo "Invalid key")
        error "Key validation failed: ${ERROR_MSG}"
        read -rp "Try a different key? [y/N]: " retry
        [[ "$retry" =~ ^[Yy]$ ]] || exit 1
        continue
    fi

    # Extract property details from response
    PROPERTY_ID=$(echo "$RESPONSE" | grep -o '"id":[0-9]*' | head -1 | cut -d: -f2)
    PROPERTY_SLUG=$(echo "$RESPONSE" | grep -o '"slug":"[^"]*"' | cut -d'"' -f4)
    PROPERTY_NAME=$(echo "$RESPONSE" | grep -o '"name":"[^"]*"' | cut -d'"' -f4)
    PROPERTY_DOMAIN=$(echo "$RESPONSE" | grep -o '"domain":"[^"]*"' | cut -d'"' -f4 || echo "")

    success "Key validated!"
    echo ""
    echo "  Property  : ${PROPERTY_NAME}"
    echo "  Slug      : ${PROPERTY_SLUG}"
    echo "  ID        : ${PROPERTY_ID}"
    [ -n "$PROPERTY_DOMAIN" ] && echo "  Domain    : ${PROPERTY_DOMAIN}"
    echo ""
    read -rp "$(echo -e "${YELLOW}Proceed with installation? [Y/n]${NC}: ")" confirm
    [[ "$confirm" =~ ^[Nn]$ ]] && exit 0
    break
done

# ── 2. JWT Secret ─────────────────────────────────────────────────────────────
echo ""
echo "The property backend must share the same JWT secret as the portal."
echo ""
read -rsp "$(echo -e "${BLUE}Enter JWT Secret${NC} (from portal .env): ")" JWT_SECRET
echo ""
if [ -z "$JWT_SECRET" ]; then
    warn "No JWT secret provided — generating a random one."
    warn "⚠️  You must update this to match the portal's JWT_SECRET!"
    JWT_SECRET=$(openssl rand -hex 32)
fi

# ── 3. Detect OS ──────────────────────────────────────────────────────────────
if [ -f /etc/os-release ]; then
    . /etc/os-release; OS_ID="${ID}"
else
    error "Cannot detect OS"; exit 1
fi
is_ubuntu() { [[ "${OS_ID}" == "ubuntu" ]]; }
is_amzn()   { [[ "${OS_ID}" == "amzn" ]]; }

info "Detected OS: ${PRETTY_NAME}"

# ── 4. System packages ────────────────────────────────────────────────────────
info "Installing system packages..."
if is_ubuntu; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq && apt-get upgrade -y -qq
    apt-get install -y -qq git curl wget nginx certbot python3-certbot-nginx \
        build-essential python3 htop ufw fail2ban
elif is_amzn; then
    dnf update -y -q
    dnf install -y git curl wget nginx htop firewalld
    pip3 install certbot certbot-nginx --quiet
    systemctl enable --now firewalld
fi
success "System packages installed"

# ── 5. Node.js ────────────────────────────────────────────────────────────────
info "Installing Node.js ${NODE_VERSION}..."
if ! command -v node &>/dev/null || [[ "$(node -v)" != v${NODE_VERSION}* ]]; then
    if is_ubuntu; then
        curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
        apt-get install -y nodejs
    elif is_amzn; then
        curl -fsSL https://rpm.nodesource.com/setup_${NODE_VERSION}.x | bash -
        dnf install -y nodejs
    fi
fi
npm install -g pm2 --silent
success "Node.js $(node -v) and PM2 installed"

# ── 6. App user & directories ─────────────────────────────────────────────────
info "Creating app user and directories..."
id "${APP_USER}" &>/dev/null || useradd -r -m -s /bin/bash "${APP_USER}"
mkdir -p "${APP_DIR}" "${DATA_DIR}" "${LOG_DIR}"
chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}"

# ── 7. EBS / data volume ──────────────────────────────────────────────────────
EBS_DEVICE="/dev/xvdb"
if [ -b "${EBS_DEVICE}" ]; then
    info "Configuring EBS data volume at ${DATA_DIR}..."
    ! blkid "${EBS_DEVICE}" &>/dev/null && mkfs -t ext4 "${EBS_DEVICE}"
    grep -q "${EBS_DEVICE}" /etc/fstab || \
        echo "${EBS_DEVICE}  ${DATA_DIR}  ext4  defaults,nofail  0  2" >> /etc/fstab
    mount -a
    success "EBS mounted at ${DATA_DIR}"
fi
chown -R "${APP_USER}:${APP_USER}" "${DATA_DIR}"

# ── 8. Clone code ─────────────────────────────────────────────────────────────
info "Cloning application code (backend only)..."
if [ -d "${APP_DIR}/.git" ]; then
    cd "${APP_DIR}" && sudo -u "${APP_USER}" git pull origin "${GIT_BRANCH}"
else
    sudo -u "${APP_USER}" git clone \
        --no-checkout --filter=blob:none \
        --branch "${GIT_BRANCH}" "${GIT_REPO}" "${APP_DIR}"
    cd "${APP_DIR}"
    sudo -u "${APP_USER}" git sparse-checkout init --cone
    sudo -u "${APP_USER}" git sparse-checkout set backend
    sudo -u "${APP_USER}" git checkout "${GIT_BRANCH}"
fi
cd "${APP_DIR}/backend"
sudo -u "${APP_USER}" npm ci --omit=dev
success "Backend code installed"

# ── 9. Write .env ─────────────────────────────────────────────────────────────
info "Writing environment configuration..."
cat > "${APP_DIR}/backend/.env" <<EOF
PROPERTY_ID=${PROPERTY_ID}
PROPERTY_SLUG=${PROPERTY_SLUG}
PROPERTY_KEY=${PROPERTY_KEY}
PORT=${APP_PORT}
NODE_ENV=production
DB_PATH=${DATA_DIR}/optima.db
JWT_SECRET=${JWT_SECRET}
ALLOWED_ORIGIN=${PORTAL_URL}
PORTAL_URL=${PORTAL_URL}
EOF
chown "${APP_USER}:${APP_USER}" "${APP_DIR}/backend/.env"
chmod 600 "${APP_DIR}/backend/.env"
success "Configuration written"

# ── 10. PM2 ───────────────────────────────────────────────────────────────────
info "Setting up PM2 process manager..."
cat > "${APP_DIR}/ecosystem.config.js" <<PMEOF
module.exports = {
  apps: [{
    name:               'optima-${PROPERTY_SLUG}',
    script:             'property-server.js',
    cwd:                '${APP_DIR}/backend',
    env_file:           '${APP_DIR}/backend/.env',
    instances:          1,
    exec_mode:          'fork',
    autorestart:        true,
    max_restarts:       10,
    restart_delay:      2000,
    max_memory_restart: '512M',
    kill_timeout:       5000,
    wait_ready:         true,
    listen_timeout:     8000,
    error_file:         '${LOG_DIR}/error.log',
    out_file:           '${LOG_DIR}/out.log',
    log_date_format:    'YYYY-MM-DD HH:mm:ss',
    merge_logs:         true,
    node_args:          '--max-old-space-size=384',
    env: { NODE_ENV: 'production' },
  }],
};
PMEOF
chown "${APP_USER}:${APP_USER}" "${APP_DIR}/ecosystem.config.js"
sudo -u "${APP_USER}" pm2 start "${APP_DIR}/ecosystem.config.js"
sudo -u "${APP_USER}" pm2 save
pm2 startup systemd -u "${APP_USER}" --hp "/home/${APP_USER}" | tail -1 | bash
success "PM2 configured and running"

# ── 11. Nginx + SSL (optional) ────────────────────────────────────────────────
if [ -n "$PROPERTY_DOMAIN" ]; then
    info "Configuring Nginx and SSL for ${PROPERTY_DOMAIN}..."
    cat > /etc/nginx/sites-available/optima-property <<NGXEOF
server {
    listen 80;
    server_name ${PROPERTY_DOMAIN};
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl http2;
    server_name ${PROPERTY_DOMAIN};
    ssl_certificate     /etc/letsencrypt/live/${PROPERTY_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${PROPERTY_DOMAIN}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    add_header Strict-Transport-Security "max-age=63072000" always;
    location /api/ {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 180s;
    }
    location = /health { proxy_pass http://127.0.0.1:${APP_PORT}/api/health; }
    location / { return 404 '{"error":"API only"}'; add_header Content-Type application/json; }
}
NGXEOF
    is_ubuntu && ln -sf /etc/nginx/sites-available/optima-property /etc/nginx/sites-enabled/optima-property && rm -f /etc/nginx/sites-enabled/default
    is_amzn && cp /etc/nginx/sites-available/optima-property /etc/nginx/conf.d/optima-property.conf
    systemctl enable --now nginx && nginx -t && systemctl reload nginx
    certbot certonly --nginx -d "${PROPERTY_DOMAIN}" \
        --non-interactive --agree-tos --email "admin@sclera.com" --no-eff-email
    nginx -t && systemctl reload nginx
    success "SSL configured for ${PROPERTY_DOMAIN}"
else
    warn "No domain configured — skipping Nginx/SSL setup"
    info "Property API available at: http://$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4 2>/dev/null || hostname -I | awk '{print $1}'):${APP_PORT}"
fi

# ── 12. Firewall ──────────────────────────────────────────────────────────────
if is_ubuntu; then
    ufw default deny incoming && ufw default allow outgoing
    ufw allow ssh && ufw allow 'Nginx Full' && ufw --force enable
elif is_amzn; then
    firewall-cmd --permanent --add-service={ssh,http,https} && firewall-cmd --reload
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║               ✅  Installation Complete!                    ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Property  : ${PROPERTY_NAME}"
printf "║  %-58s║\n" "ID: ${PROPERTY_ID}  |  Slug: ${PROPERTY_SLUG}"
[ -n "$PROPERTY_DOMAIN" ] && printf "║  %-58s║\n" "API: https://${PROPERTY_DOMAIN}/api/health" \
  || printf "║  %-58s║\n" "Internal API: http://localhost:${APP_PORT}/api/health"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Register this server in the portal:                        ║"
PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4 2>/dev/null || hostname -I | awk '{print $1}')
printf "║  Server URL: %-46s║\n" "http://${PRIVATE_IP}:${APP_PORT}"
echo "║  → Login to ${PORTAL_URL}                    "
echo "║  → Property List → Add Property → paste the Server URL     ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Commands:                                                  ║"
echo "║    pm2 status              — process status                 ║"
echo "║    pm2 logs optima-${PROPERTY_SLUG}   — view logs            "
echo "║    pm2 reload optima-${PROPERTY_SLUG} — zero-downtime reload "
echo "╚══════════════════════════════════════════════════════════════╝"
